print("")
first = input("What is the first number? ")
print("")
second = input("What is the second number? ")
print("")
sum = float(first) + float(second)
print("")
print("The total number is: " + str(sum))
print("")