print("")
name = input("What is your name? ")
print("")
print("Hello " + name)
print("")
full_name = input("What is your full name? ")
print("")
print("Excellent, thank you " + full_name)
print("")
birth_year = input("Enter your birth year to continue: ")
print("")
age = 2020 - int(birth_year)
print("")
print("Your age is " + age)
print("")