price = 25
print(price > 10 and price < 30)
value = 15
print(value > 10 or price < 30)
print("")
temp = float(input("What is the temperature today? "))
print("")
if temp > 40:
    print("Stay in the shade today, it is extremely hot in the sun.")
    print("The temperature has gone above 40 degrees.")
elif temp > 30: # (30, 40)
    print("It's a hot day today, make sure you drink lots of water and wear sun cream.")
    print("Please be safe in this hot weather.")
elif temp > 20: # (20, 30)
    print("It is a nice day today, with average to warm temperatures.")
    print("Shorts can still be worn.")
elif temp > 10: # (10, 20)
    print("It is a colder day today.")
    print("You may need to wear a jumper.")
elif temp > 0: # (0, 10)
    print("It is colder than 10 degrees today.")
    print("Please make sure you wear warm clothes in this weather.")
elif temp > -10: # (-10, 0)
    print("It is freezing cold weather today.")
    print("Thermal clothing will be required when heading outside today, to avoid frostbite.")
print("")
print("Done")
print("")